[package]
name = "min"
version = "0.1.2"
edition = "2021"
readme = "../README.md"
repository = "https://github.com/Reed-Broadhead/Min"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
webp = "0.2"
image = "0.25.5"

